app/video/forms.py
from flask_wtf import FlaskForm
from wtforms import FileField, SubmitField, StringField, SelectField
from flask_wtf.file import FileRequired, FileAllowed
from wtforms.validators import DataRequired, Length, NumberRange
from flask_uploads import IMAGES
from config import video_selects


class VideoForm(FlaskForm):
    video = FileField('视频', validators=[FileRequired(), FileAllowed(['mp4'])])  # gif仅用于测试
    title = StringField('标题', validators=[DataRequired('请输入标题'), Length(2, 31)])
    face = FileField('封面', validators=[FileRequired(), FileAllowed(IMAGES)])
    desc = StringField('简介', validators=[Length(0, 63)])
    type = SelectField(label='分区',
                       coerce=int,
                       choices=video_selects,
                       validators=[DataRequired('请选择分区')])
    submit = SubmitField('上传')

app/video/__init__.py
from flask import Blueprint

video = Blueprint('video', __name__)

from . import views  # 写后面避免views, errors循环导入

app/video/views.py
from flask import render_template, redirect, url_for, request, current_app, abort
from . import video
from .forms import VideoForm
from ..models import Video, Comment, Permission, Log
from .. import db, up_files
from ..decorators import permission_required
from flask_login import current_user, login_required
from os import remove
from datetime import datetime


@video.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    form = VideoForm()
    if form.validate_on_submit():
        v_file = request.files['video']
        v_face = form.face.data  # 两种方法都可
        max_id = db.session.execute('select max(id) from videos').fetchone()  # '..RowProxy' tuple形式(2,)
        max_num = str((0 if not max_id[0] else max_id[0]) + 1)
        filename = max_num + '.' + v_file.filename.rsplit('.')[1]
        facename = max_num + '.' + v_face.filename.rsplit('.')[1]

        new_video = Video(title=form.title.data,
                          file=filename,
                          author_id=current_user.id,
                          type=form.type.data,
                          face=facename,
                          desc=form.desc.data)  # title=form.title出错
        up_files.save(v_file, name=f'videos/{filename}')
        up_files.save(v_face, name=f'video_faces/{facename}')
        log = Log(uid=current_user.id, op=2, detail=f'av {max_num}')
        db.session.add_all([new_video, log])
        db.session.commit()

        return redirect(url_for('video.manage'))
    return render_template('video/upload.html', form=form)


@video.route('/reload', methods=['POST'])
@login_required
def reload():
    form = VideoForm()
    if form.validate_on_submit():
        av = request.form['av']
        bideo = Video.query.filter_by(id=av).first()
        v_file = form.video.data
        v_face = form.face.data

        if v_file:
            remove(current_app.config['UPLOADED_FILES_DEST'] + 'videos/' + bideo.file)
            bideo.file = str(bideo.id) + '.' + v_file.filename.rsplit('.')[1]
            up_files.save(v_file, name=f'videos/{bideo.file}')
            bideo.like = bideo.coin = bideo.collect = 0
        if v_face:
            remove(current_app.config['UPLOADED_FILES_DEST'] + 'video_faces/' + bideo.face)
            bideo.face = str(bideo.id) + '.' + v_face.filename.rsplit('.')[1]
            up_files.save(v_face, name=f'video_faces/{bideo.face}')

        bideo.title = form.title.data
        bideo.desc = form.desc.data
        bideo.type = form.type.data
        bideo.status = 0  # 需重新审核
        bideo.date = datetime.now()
        log = Log(uid=current_user.id, op=2, detail=f'av {av}')
        db.session.add_all([bideo, log])
        db.session.commit()
    return 'success'


@video.route('/manage', methods=['GET', 'POST'])
@login_required
def manage():
    form = VideoForm()
    if request.method == 'POST':
        av = request.get_data().decode('utf-8')
        v = Video.query.filter_by(id=av).first()
        log = Log(uid=current_user.id, op=4, detail=f'av {av}')
        db.session.add(log)
        db.session.delete(v)
        db.session.commit()
        return 'success'
    # bideo = current_user.videos.all()
    page = request.args.get('page', 1, type=int)
    pagination = current_user.videos.order_by(Video.date.desc()).paginate(
        page=page,
        per_page=current_app.config['CYAKKA_VIDEO_PER_PAGE']
    )
    bideo = pagination.items
    return render_template('video/manage.html', videos=bideo, pagination=pagination, form=form)


@video.route('/<string:v_type>')
def classify(v_type):
    type_tuple = current_app.config['CYAKKA_VIDEO_TYPES'].get(v_type)
    if not type_tuple:
        abort(404)
    page = request.args.get('page', 1, type=int)
    pagination = Video.query.filter_by(type=str(type_tuple[0]), status=1).order_by(Video.date.desc()).paginate(
        page=page,
        per_page=current_app.config['CYAKKA_VIDEO_PER_PAGE']
    )
    bideo = pagination.items
    return render_template('video/divisions.html', v_type=v_type,
                           v_types=current_app.config['CYAKKA_VIDEO_TYPES'],
                           videos=bideo,
                           pagination=pagination)


@video.route('/av<int:av>')
def play(av):
    bideo = Video.query.get_or_404(av)  # 应是完整文件名
    if bideo.status != 1 and not current_user.can(Permission.AUDIT):  # 审核中或者审核未通过需auditor才能看
        abort(404)
    v_type = list(current_app.config['CYAKKA_VIDEO_TYPES'].values())[bideo.type-1][1]

    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (bideo.comments.count() - 1)//current_app.config['CYAKKA_COMM_PER_PAGE'] + 1
    pagination = bideo.comments.order_by(Comment.date.asc()).paginate(
        page=page,
        per_page=current_app.config['CYAKKA_COMM_PER_PAGE'],
        error_out=False
    )
    comms = pagination.items
    return render_template('video/play.html', video=bideo, v_type=v_type, comments=comms, pagination=pagination)


@video.route('/comment', methods=['POST'])
@login_required
@permission_required(Permission.COMMENT)
def comment():
    av = request.args.get('av', type=int)
    bideo = Video.query.get_or_404(av)
    if bideo.status is not 1:
        return 'video status error'

    comm_body = request.get_data()
    comm = Comment(body=comm_body,
                   author=current_user._get_current_object(),
                   video=bideo)
    db.session.add(comm)
    db.session.commit()
    # return redirect(url_for('video.comment', av=av, page=-1))  # -1表示最后一页
    return 'success'


@video.route('/comment/tip', methods=['POST'])
@login_required
@permission_required(Permission.COMMENT)
def tip_comment():
    if request.method == 'POST':
        cid = request.get_data()
        comm = Comment.query.filter_by(id=cid).first()
        if not comm or comm.tipped:
            abort(403)  # 不存在的或已举报
        comm.tipped = True
        comm.tip_user = current_user.id
        db.session.add(comm)
        db.session.commit()
        return 'success'


@video.route('/ops_<string:action>', methods=['POST'])
@login_required
@permission_required(Permission.COMMENT)
def alter_statistic(action):
    if action not in ['like', 'collect', 'coin']:
        return 'action type error'
    light_on = eval(request.form[action].capitalize())  # 当前是否点亮
    av = request.form['av']
    bideo = Video.query.get_or_404(av)

    if bideo.status is not 1:
        return 'video status error'
    # bideo.like += [-1, 1][like]
    if action == 'like' and light_on:
        bideo.like -= 1
        current_user.v_like.remove(bideo)
        log = Log.query.filter(Log.uid == current_user.id, Log.op == 3, Log.detail == f'av {av}').first()
        db.session.delete(log)
    elif action == 'like' and not light_on:
        bideo.like += 1
        current_user.v_like.append(bideo)
        log = Log(uid=current_user.id, op=3, detail=f'av {av}')
        db.session.add(log)
    if action == 'collect' and light_on:
        bideo.collect -= 1
        current_user.v_collect.remove(bideo)
    elif action == 'collect' and not light_on:
        bideo.collect += 1
        current_user.v_collect.append(bideo)
    if action == 'coin' and not light_on and current_user.coins >= 1:
        current_user.coins -= 1
        bideo.coin += 1
        current_user.v_coin.append(bideo)
    elif action == 'coin':
        return 'no refunds or coins run out'

    db.session.add_all([bideo, current_user._get_current_object()])
    db.session.commit()
    return 'success'


@video.route('/is_<string:action>')
def confirm_statistic(action):
    if not current_user.is_authenticated:
        return 'None'  # 装饰器会返回登录html，而非None
    av = request.args.get('av', type=int)
    if action == 'like':
        return current_user.v_like.filter_by(id=av).first().__repr__()
    elif action == 'coin':
        return current_user.v_coin.filter_by(id=av).first().__repr__()
    elif action == 'collect':
        return current_user.v_collect.filter_by(id=av).first().__repr__()
    return 'Error'

app/templates/video/_comment.html
{% import "_macros.html" as macros %}

<div id="v-comment">
    <h4>{{ video.comments.count() }}  评论</h4>
    <div class="comm-send">
        <div class="user-face">
            {% if current_user.is_authenticated and current_user.avatar %}
                <img class="img-circle" src="../../static/avatars/{{ current_user.avatar }}" >
            {% else %}
                <img class="img-circle" src="../../static/avatars/noface.gif" >
            {% endif %}
        </div>
        <button type="submit" class="comm-submit" {% if not current_user.is_authenticated %}disabled{% endif %}>发表评论</button>
        {% if current_user.is_authenticated %}
            <textarea class="comm-input" maxlength="150" cols="80" rows="5" placeholder="请自觉遵守互联网相关的政策法规，严禁发布色情、暴力、反动的言论。" ></textarea>
        {% else %}
            <div class="comm-input" style="text-align: center; vertical-align: center">
                请先<a href="{{ url_for('auth.login') }}">登录</a>后发表评论(・ω・)
            </div>
        {% endif %}
    </div>

    <div class="comm-list">
        {% for comm in comments %}
            <div class="comm-item" data-cid="{{ comm.id }}">
                <div class="user-face"><a href="{{ url_for('main.user_space', uid=comm.author_id)}}">
                    {% if comm.author.avatar %}
                        <img class="img-circle" src="../../static/avatars/{{ comm.author.avatar }}">
                    {% else %}
                        <img class="img-circle" src="../../static/avatars/default.jpg">
                    {% endif %}
                </a></div>
                <div class="con">
                    <a class="user-info" href="{{ url_for('main.user_space', uid=comm.author_id)}}" target="_blank">{{ comm.author.nickname }}</a>
                    <p class="text">{{ comm.body }}</p>
                    <div class="info">
                        <span class="time">{{ comm.date }}</span>
                        <span class="tip-off">举报</span>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if not comments %}
            <div class="no-comm">看看下面~来发评论吧</div>
        {% endif %}
    </div>

    <div class="pagination">
        {{ macros.pagination_widget(pagination, 'video.play',  {"av":video.id}) }}
    </div>
</div>

app/templates/video/divisions.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}{{ v_types[v_type][1] }} - Cyakka{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="../../static/css/video.css">
{% endblock %}

{% block nav_menu %}
    {{ super() }}
    <div class="navbar-collapse collapse primary-menu">
        <ul class="nav nav-tabs">
            {% for key, value in v_types.items() %}
                <li><a href="{{ url_for('video.classify', v_type=key) }}">{{ value[1] }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div class="video-box">

        {% include "_videolist.html" %}

        <div class="pagination">
            {{ macros.pagination_widget(pagination, 'video.classify', {"v_type": v_type}) }}
        </div>
    </div>
    {{ super() }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="../../static/js/video.js"></script>
{% endblock scripts %}

app/templates/video/manage.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}我的投稿 - Cyakka{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="../static/css/video.css">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="vd-list"><ul>
            {% for v in videos %}
            <li data-av="{{ v.id }}" data-div="{{ v.type }}">
                <div class="left"><a href="{{ url_for('video.play', av=v.id) }}">
                    <img src="../../static/video_faces/{{ v.face }}" alt="{{ v.title }}"/>
                </a></div>
                <div class="right">
                    <a href="{{ url_for('video.play', av=v.id) }}" target="_blank" class="title">{{ v.title }}</a>
                    <div class="up-info">
                        <span href="" class="v-status stat-{{ v.status }}">
{#                            {% if v.status==0 %}待审核{% elif v.status==1 %}通过{% elif v.status==2 %}违规{% endif %}#}
                            {{ macros.video_status(v.status) }}
                        </span>
                        <span class="v-date">{{ v.date }}</span>
                    </div>
                    <div class="v-desc">{% if v.desc%}{{ v.desc }}{% else %}{{ '来点简介' }}{% endif %}</div>
                    <div class="v-stat">
                        <span title="点赞数" class="like">
                            <span class="glyphicon glyphicon-thumbs-up"></span>
                            <span class="statistic">{{ macros.v_trunc(v.like) }}</span>
                        </span>
                        <span title="硬币数" class="coin">
                            <span class="glyphicon glyphicon-copyright-mark"></span>
                            <span class="statistic">{{ macros.v_trunc(v.coin) }}</span>
                        </span>
                        <span title="收藏数" class="collect">
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="statistic">{{ macros.v_trunc(v.collect) }}</span>
                        </span>
                    </div>
                    <div class="v-edit">
                        <button class="btn btn-default" data-toggle="modal" data-target="#edit-modal">编辑</button>
                        <button class="btn btn-danger">删除</button>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul></div>

        <div id="edit-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times</button>
                        <h4 class="modal-title">编辑稿件</h4>
                    </div>
                    <div class="modal-body">
{#                        <label><span>标题</span><input type="text" class="v-title"></label>#}
{#                        <label><span>封面</span><input type="file" class="v-face"></label>#}
{#                        <label><span>简介</span><input type="text" class="v-desc"></label>#}
                        {{ wtf.quick_form(form) }}
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-primary">保存</button>
                        <button class="btn btn-default" data-dismiss="modal">关闭</button>
                    </div>
                </div>
            </div>
        </div>
{#        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#edit-modal">#}
{#            Launch demo modal#}
{#        </button>#}

        <div class="pagination">
            {{ macros.pagination_widget(pagination, 'video.manage') }}
        </div>
    </div>
    {{ super() }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="../static/js/video.js"></script>
{%- endblock scripts %}

app/templates/video/play.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}{{ video.title }} - Cyakka{% endblock %}

{% block styles %}
    {{ super() }}
    <link href="../../static/css/DPlayer.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../../static/css/video.css">
{% endblock %}

{% block content %}
<div class="container left-con">
    <div id="view-box">
        <h4>{{ video.title }}</h4>
        <div class="v-info">
            <a class="first" href="{{ url_for('video.classify', v_type=v_type) }}">{{ v_type }}</a>
            <span>{{ video.date }}</span>
        </div>
        <div class="v-info">
            <span class="first">播放数</span><span>弹幕数</span>
        </div>
    </div>

    <div id="player-wrap">
        <div id="dplayer" data-file="{{ video.file }}" data-face="{{ video.face }}"
         data-id="{{ video.id }}" data-user="{{ current_user.username }}"></div>
    </div>

    <div id="v-toolbar">
        <div class="ops">
            <span title="点赞数" class="like">
                <span class="glyphicon glyphicon-thumbs-up"></span>
                <span class="statistic">{{ macros.v_trunc(video.like) }}</span>
            </span>
            <span title="硬币数" class="coin">
                <span class="glyphicon glyphicon-copyright-mark"></span>
                <span class="statistic">{{ macros.v_trunc(video.coin) }}</span>
            </span>
            <span title="收藏数" class="collect">
                <span class="glyphicon glyphicon-star"></span>
                <span class="statistic">{{ macros.v_trunc(video.collect) }}</span>
            </span>
        </div>
    </div>

    <div id="v-desc">
        <div class="desc">{{ video.desc }}</div>
        <div class="btn-more">展开更多</div>
    </div>

    {% include "video/_comment.html" %}
{#    但不会对.comment有get请求，因此comments不能在.comment提交#}
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="../../static/js/DPlayer.min.js"></script>
{#    <script src="../../static/js/md5.min.js"></script>#} <!-- 使用外部弹幕接口才需要 -->
    <script src="../../static/js/video.js" defer></script>
{% endblock scripts %}

app/templates/video/upload.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}视频投稿 - {{ current_user.username }} - Cyakka{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="../../static/css/video.css">
{% endblock %}

{% block content %}
    <div class="upload-box">
        <h1>Upload-Video</h1>
        <div class="upload-form">{{ wtf.quick_form(form) }}</div>
    </div>
    {{ super() }}
{% endblock %}


{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="../../static/js/video.js"></script>
{% endblock scripts %}