app/main/__init__.py
from flask import Blueprint
from ..models import Permission

main = Blueprint('main', __name__)


@main.app_context_processor  # 上下文处理器，使Permission能在模板中使用
def inject_permissions():
    return dict(Permission=Permission)


from . import views, errors, api  # 写后面避免views, errors循环导入

app/main/views.py
from flask import render_template, flash, redirect, url_for, request, current_app, abort, jsonify
from . import main
from ..decorators import admin_required, permission_required
from ..models import User, Video, Permission, Comment, Perm_choices, Log, Log_ops
from .forms import ProfileForm, ProfileAdminForm, AvatarForm, AlterAuthForm, SearchForm, LogForm
from flask_login import current_user, login_required
from .. import db, up_files, redis_db
from os import remove
from sqlalchemy import func


@main.route('/')
def index():
    v_types = current_app.config['CYAKKA_VIDEO_TYPES']
    v_divs = dict()
    div = request.args.get('div', type=str)

    if div in v_types.keys():
        videos = Video.query.filter_by(type=v_types[div][0], status=1).order_by(func.rand()).limit(10)
        return render_template('_indexshows.html', v_divs=videos)

    # for i in range(1, len(v_types)+1):
    for k, v in v_types.items():
        v_divs[k] = Video.query.filter_by(type=v[0], status=1).order_by(func.rand()).limit(10)
    return render_template('index.html', v_divs=v_divs, v_types=v_types)


@main.route('/space/<int:uid>')
def user_space(uid):
    user = User.query.filter_by(id=uid).first_or_404()
    div = request.args.get('div', type=str)
    page = request.args.get('page', 1, type=int)
    up = Video.query.filter_by(author_id=user.id, status=1)
    coll = user.v_collect

    if div not in ['upload', 'collect']:   # 当作请求主页
        videos = dict()
        videos['upload'] = up.order_by(Video.date.desc()).limit(10)
        videos['collect'] = coll.order_by(Video.date.desc()).limit(10)
        return render_template('main/space.html', user=user, videos=videos)
    else:
        query = [up, coll][div == 'collect']
        pagination = query.order_by(Video.date.desc()).paginate(
            page=page,
            per_page=current_app.config['CYAKKA_VIDEO_PER_PAGE']
        )
        return render_template('main/_spaceshow.html', videos=pagination.items,
                               uid=user.id, v_div=div, pagination=pagination)


@main.route('/search')
def search():
    form = SearchForm()
    keyword = request.args.get('keyword')
    if not keyword:
        return render_template('main/search.html', form=form)

    s_type = request.args.get('type', 'videos')
    s_order = request.args.get('order', 'all')
    s_div = request.args.get('div', 'all')
    s_anchor = request.args.get('anchor', 'name')
    page = request.args.get('page', 1, type=int)
    model = [User, Video][s_type == 'videos']
    query = model.query

    if s_type == 'videos':
        form.order.data = s_order
        form.div.data = s_div

        for kw in keyword.split():
            query = query.filter(model.title.contains(kw))

        if s_order == 'new':
            query = query.order_by(model.date.desc())
        elif s_order == 'like':
            query = query.order_by(model.like.desc())
        elif s_order == 'collect':
            query = query.order_by(model.collect.desc())
        elif s_order == 'all':
            query = query.order_by(model.like.desc(), model.collect.desc(), model.date.desc())
            # 排序结果与三参数相对位置有关
        if s_div != 'all':
            query = query.filter_by(type=current_app.config['CYAKKA_VIDEO_TYPES'][s_div][0])
        query = query.filter_by(status=1)

    elif s_type == 'users':
        form.anchor.data = s_anchor

        if s_anchor == 'name':
            for kw in keyword.split():
                query = query.filter(model.nickname.contains(kw))
        elif s_anchor == 'id':
            try:
                uid = int(keyword)
            except ValueError:
                uid = 0  # 不存在的id
            query = query.filter(model.id == uid)

    pagination = query.paginate(
        page=page,
        per_page=current_app.config['CYAKKA_VIDEO_PER_PAGE']
    )
    items = dict()
    items[s_type] = pagination.items or 'nil'
    form.keyword.data = keyword
    form.type.data = s_type
    return render_template('main/search.html', form=form, pagination=pagination, **items)


@main.route('/search/history', methods=['GET', 'POST', 'DELETE'])
def search_history():
    if current_user.is_anonymous:
        key = 'search_history_anonymous'
    else:
        key = f'search_history_{current_user.id}'
    response = dict()
    kw = request.form.get('keyword', '')

    if request.method == 'POST':
        redis_db.lrem(key, 0, kw)  # 删除所有值为kw的记录(若有)
        redis_db.lpush(key, kw)  # 再将kw插入顶部
        redis_db.ltrim(key, 0, 5)  # 仅保留6条记录(区间0-5)
        return 'finish'

    if request.method == 'DELETE':
        redis_db.lrem(key, 0, kw)
        return 'success'

    history = [x.decode() for x in redis_db.lrange(key, 0, 5)]
    response['history'] = history
    return jsonify(response)


@main.route('/back/log-user')
@admin_required
def log_user():
    form = LogForm()
    uid = request.args.get('uid', type=int)
    op = request.args.get('op')
    page = request.args.get('page', 1, type=int)
    if not uid or not op:
        return render_template('main/log_user.html', form=form)

    pagination = Log.query.filter(Log.uid == uid, Log.op == Log_ops.index(op)).paginate(
        page=page,
        per_page=current_app.config['CYAKKA_VIDEO_PER_PAGE']
    )
    form.uid.data = uid
    form.op.data = op
    logs = pagination.items
    return render_template('main/log_user.html', form=form, logs=logs, pagination=pagination)


@main.route('/back/log-admin')
@admin_required
def log_admin():
    op = request.args.get('op')
    page = request.args.get('page', 1, type=int)
    if not op or op not in ['login', 'edit', 'audit', 'register']:
        return render_template('main/log_admin.html')

    if op == 'login' or op == 'edit':
        query = Log.query.filter(Log.op == Log_ops.index(op)).order_by(Log.date.desc())
    elif op == 'audit':
        query = Video.query.filter(Video.status != 0).order_by(Video.date.desc())  # 审核过的
    else:
        query = User.query.order_by(User.member_since.desc())

    pagination = query.paginate(
        page=page,
        per_page=current_app.config['CYAKKA_VIDEO_PER_PAGE']
    )
    items = pagination.items
    return render_template('main/log_admin.html', logs=items, op=op, pagination=pagination)


# 若 "/back/audit/video之类的三级path会导致继承来的样式中用到相对路径的失效
@main.route('/back/audit-video', methods=['GET', 'POST'])
@permission_required(Permission.AUDIT)
def audit_video():
    if request.method == 'POST':
        av = request.form['av']
        status = int(request.form['status'])
        v = Video.query.filter_by(id=av).first()
        v.status = status
        v.inspector = current_user.id
        db.session.add(v)
        db.session.commit()
        return 'success'
    page = request.args.get('page', 1, type=int)
    pagination = Video.query.filter_by(status=0).paginate(
        page=page,
        per_page=current_app.config['CYAKKA_VIDEO_PER_PAGE']
    )
    bideo = pagination.items
    return render_template('main/video_audit.html', videos=bideo, pagination=pagination)


@main.route('/back/audit-comment', methods=['GET', 'POST'])
@permission_required(Permission.AUDIT)
def audit_comment():
    if request.method == 'POST':
        cid = request.form['cid']
        op = request.form['op']
        comm = Comment.query.filter_by(id=cid).first()
        if op == '0':  # 禁言发言者
            db.session.delete(comm)
            comm.author.permissions &= ~Permission.COMMENT
        elif op == '1':  # 禁言(第一个)举报者
            comm.tipped = False
            db.session.add(comm)
            tip_user = User.query.filter_by(id=comm.tip_user).first()
            tip_user.permissions &= ~Permission.COMMENT
        db.session.commit()
        return 'finish'
    page = request.args.get('page', 1, type=int)
    pagination = Comment.query.filter_by(tipped=True).paginate(
        page=page,
        per_page=current_app.config['CYAKKA_COMM_PER_PAGE']
    )
    comm = pagination.items
    return render_template('main/comm_manage.html', comments=comm, pagination=pagination)


@main.route('/back/audit-user', methods=['GET', 'POST'])
@permission_required(Permission.ADMIN)
def audit_user():
    page = request.args.get('page', 1, type=int)
    pagination = User.query.order_by(User.member_since.asc()).paginate(
        page=page,
        per_page=current_app.config['CYAKKA_VIDEO_PER_PAGE']
    )
    users = pagination.items
    return render_template('main/user_manage.html', users=users, pagination=pagination)


@main.route('/edit/password', methods=['GET', 'POST'])
@login_required
def edit_password():
    form = AlterAuthForm(user=current_user)
    if form.validate_on_submit():
        current_user.password = form.password2.data
        db.session.add(current_user._get_current_object())  # current.user似乎是包装后的对象
        db.session.commit()
        flash('修改成功')
        return redirect(url_for('.user_space', uid=current_user.id))
    return render_template('main/edit_password.html', form=form)


@main.route('/edit/avatar', methods=['GET', 'POST'])
@login_required
def edit_avatar():
    form = AvatarForm()
    if form.validate_on_submit():
        avatar = request.files['avatar']  # avatar为文件字段的name属性值
        ext = avatar.filename.rsplit('.')[1]
        filename = f'{current_user.id}.' + ext

        if up_files.file_allowed(avatar, ext):
            abort(413)
        if current_user.avatar:
            remove(current_app.config['UPLOADED_FILES_DEST'] + 'avatars/' + current_user.avatar)

        up_files.save(avatar, name=f'avatars/{filename}')
        current_user.avatar = filename
        db.session.add(current_user._get_current_object())
        db.session.commit()
        return redirect(url_for('.user_space', uid=current_user.id))

app/templates/main/_spaceshow.html
{% import "_macros.html" as macros %}


{% include "_videolist.html" %}

<div class="pagination">
    {{ macros.pagination_widget(pagination, 'main.user_space', {'uid':uid, 'div':v_div}) }}
</div>

app/templates/main/backstage.html
{% extends "base.html" %}

{% block title %}后台管理 - Cyakka{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="../../static/css/main.css">
{% endblock %}

{% block content %}
    <div id="back-nav" class="btn-group-vertical">
        <a class="btn" href="{{ url_for('main.audit_video') }}">稿件审核</a>
        <a class="btn" href="{{ url_for('main.audit_comment') }}">评论管理</a> {# <处理被举报的评论...>#}
        {% if current_user.is_administrator() %}
            <a class="btn" href="{{ url_for('main.audit_user') }}">用户管理</a> {# <分页列出所有用户...>#}
            <a class="btn" href="{{ url_for('main.log_user') }}">用户日志</a>
            <a class="btn" href="{{ url_for('main.log_admin', op='login') }}">管理日志</a>
            {# 用户意见 管理团队#}
        {% endif %}
    </div>
    {{ super() }}
{% endblock %}


{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="../../static/js/main.js"></script>
{% endblock scripts %}

app/templates/main/comm_manage.html
{% extends "main/backstage.html" %}
{% import "_macros.html" as macros %}

{% block content %}
    {{ super() }}
    <div id="back-body" class="back-box">
    {% for comm in comments %}
        <div class="comm-item" data-cid="{{ comm.id }}">
            <div class="user-face"><a href="{{ url_for('main.user_space', uid=comm.author_id)}}">
                {% if comm.author.avatar %}
                    <img class="img-circle" src="../../static/avatars/{{ comm.author.avatar }}">
                {% else %}
                    <img class="img-circle" src="../../static/avatars/default.jpg">
                {% endif %}
            </a></div>
            <div class="con">
                <a class="user-info" href="{{ url_for('main.user_space', uid=comm.author_id)}}" target="_blank">{{ comm.author.nickname }}</a>
                <p class="text">{{ comm.body }}</p>
                <div class="info">
                    <span class="time">{{ comm.date }}</span>
                    <span class="glyphicon glyphicon-ok" title="举报不成立，惩处举报者"></span>
                    <span class="glyphicon glyphicon-remove" title="举报成立，惩处发言者"></span>
                </div>
            </div>
        </div>
    {% endfor %}

        <div class="pagination">
            {{ macros.pagination_widget(pagination, 'main.audit_video') }}
        </div>
    </div>
{% endblock %}

app/templates/main/log_admin.html
{% extends "main/backstage.html" %}
{% import "_macros.html" as macros %}

{% block title %}管理日志 - Cyakka{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="../../static/css/main.css">
{% endblock %}

{% block content %}
    <div id="log-body" class="back-box">
        <form class="log-form">
            <nav class="search-nav">
                <ul class="filter-type" id="op">
                    <li><input id="op-0" name="op" type="radio" value="login">
                        <label for="op-0">登录记录</label>
                    </li>
                    <li><input id="op-1" name="op" type="radio" value="register">
                        <label for="op-1">用户注册</label>
                    </li>
                    <li><input id="op-2" name="op" type="radio" value="edit">
                        <label for="op-2">编辑用户</label>
                    </li>
                    <li><input id="op-3" name="op" type="radio" value="audit">
                        <label for="op-3">审核稿件</label>
                    </li>
                </ul>
            </nav>
        </form>

        <table class="table">
        <tr>
            <th class="col-md-2">时间</th>
            <th class="col-md-2">UID</th>
            <th class="col-md-3">详细信息</th>
        </tr>

        {% for log in logs %}
        <tr class="user-info">
            {% if log.uid %} {# log 登录/修改 #}
                <td class="col-md-2">{{ log.date }}</td>
                <td class="col-md-2"><a href="{{ url_for('main.user_space', uid=log.uid) }}" target="_blank">{{ log.uid }}</a></td>
                <td class="col-md-3">{{ log.detail }}</td>

            {% elif log.inspector %} {# video 审核 #}
                <td class="col-md-2">{{ log.date }}</td>
                <td class="col-md-2"><a href="{{ url_for('main.user_space', uid=log.inspector) }}" target="_blank">{{ log.inspector }}</a></td>
                <td class="col-md-3"><a href="{{ url_for('video.play', av=log.id) }}" target="_blank">av{{ log.id }}</a>{{ macros.video_status(log.status) }}</td>

            {% else %} {# user 创建 #}
                <td class="col-md-2">{{ log.member_since }}</td>
                <td class="col-md-2"><a href="{{ url_for('main.user_space', uid=log.id) }}" target="_blank">{{ log.id }}</a></td>
                <td class="col-md-3">{{ log.username }}</td>
            {% endif %}
        {% endfor %}
        </tr>
        </table>

        {% if pagination %}
            <div class="pagination">
                {{ macros.pagination_widget(pagination, 'main.log_admin', {"op": op}) }}
            </div>
        {% endif %}
    </div>

    {{ super() }}
{% endblock %}

{#{% block scripts %}#}
{#    {{ super() }}#}
{#{% endblock scripts %}#}

app/templates/main/log_user.html
{% extends "main/backstage.html" %}
{% import "_macros.html" as macros %}

{% block title %}用户日志 - Cyakka{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="../../static/css/main.css">
{% endblock %}

{% block content %}
    <div id="log-body" class="back-box">
        <form class="log-form">
            <nav class="search-nav">
                {{ form.op(class="filter-type") }}
            </nav>
            <div class="search-input">
                {{ form.uid(placeholder="请输入需查询的用户id", autocomplete="off", maxlength="11") }}
{#                <span class="label label-primary"><span class="glyphicon glyphicon-search"></span>查找</span>#}
                <p class="light-on"></p>
            </div>
        </form>

        <table class="table">
        <tr>
            <th class="col-md-2">时间</th>
            <th class="col-md-2">用户ID</th>
            <th class="col-md-7">详细信息</th>
        </tr>
        {% for log in logs %}
        <tr class="user-info">
            <td class="col-md-2">{{ log.date }}</td>
            <td class="col-md-2"><a href="{{ url_for('main.user_space', uid=log.uid) }}" target="_blank">{{ log.uid }}</a></td>
            <td class="col-md-7">{{ log.detail }}</td>
        </tr>
        {% endfor %}
        </table>

        {% if pagination %}
            <div class="pagination">
                {{ macros.pagination_widget(pagination, 'main.log_user') }}
            </div>
        {% endif %}
    </div>

    {{ super() }}
{% endblock %}

{#{% block scripts %}#}
{#    {{ super() }}#}
{#{% endblock scripts %}#}

app/templates/main/search.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}搜索 - Cyakka{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="../../static/css/main.css">
{% endblock %}

{% block content %}
    <div id="server-search">
        <form class="search-form">
            <header>
                {{ form.keyword(id="search-input", autocomplete="off", maxlength="50", accesskey="s") }}
                <span class="label label-aka"><span class="glyphicon glyphicon-search"></span>搜索</span>
            </header>

            <nav class="search-nav">
                {{ form.type(class="filter-type nav") }}
            </nav>

            {% if videos %}
                <div class="search-filter">
                    {{ form.order(class="filter-type order") }}
                    {{ form.div(class="filter-type divs") }}
                </div>
            {% elif users %}
                <div class="search-filter">
                    {{ form.anchor(class="filter-type anchor") }}
                </div>
            {% endif %}
        </form>

        <ul class="search-history"></ul>

        {% if videos and videos != 'nil' %}
            {% include "_videolist.html" %}
        {% elif users and users != 'nil' %}
            <ul class="user-list">
                {% for user in users %}
                <li>
                    <div class="left"><a href="{{ url_for('main.user_space', uid=user.id)}}">
                    {% if user.avatar %}
                        <img class="img-circle" src="../../static/avatars/{{ user.avatar }}" alt="{{ user.nickname }}">
                    {% else %}
                        <img class="img-circle" src="../../static/avatars/default.jpg" alt="{{ user.nickname }}">
                    {% endif %}
                    </a></div>

                    <div class="right">
                        <div class="u-info">
                            <a href="{{ url_for('main.user_space', uid=user.id)}}" target="_blank">{{ user.nickname }}</a>
                            {% if user.can(Permission.ADMIN) %} <span class="label label-danger">管理</span>
                            {% elif user.can(Permission.AUDIT) %} <span class="label label-warning">审核</span>
                            {% elif user.can(Permission.VIP) %} <span class="label label-primary">大会员</span>
                            {% elif not user.permissions %} <span class="label label-default">封禁中</span>
                            {% elif user.can(Permission.LOGIN) and user.can(Permission.COMMENT) %} <span class="label label-info">会员</span>
                            {% elif not user.can(Permission.COMMENT) %} <span class="label label-success">禁言中</span>
                            {% endif %}
                        </div>
                        <div class="desc">{{ user.about_me }}</div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        {% else  %}
            <p class="no-found">未找到</p>
        {% endif %}

        {% if pagination %}
            <div class="pagination">
                {{ macros.pagination_widget(pagination, 'video.classify', {"v_type": v_type}) }}
            </div>
        {% endif %}
    </div>

    {{ super() }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="../../static/js/main.js"></script>
{% endblock scripts %}

app/templates/main/space.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}{{ user.username }}的个人空间 - Cyakka{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="../../static/css/main.css">
{% endblock %}

{% block content %}
    <div class="user-box">
        <header>
            <div class="u-avatar">
                <a href="{{ url_for('main.edit_avatar') }}" target="_blank">更换头像</a>
                {% if not user.avatar %}
                    <img src="../../static/avatars/default.jpg" class="img-circle" alt="avatar">
                {% else %}
                    <img src="../../static/avatars/{{user.avatar}}" class="img-circle" alt="avatar">
                {% endif %}
            </div>

            <div class="u-basic">
                <p class="u-name">{{ user.nickname }}</p>
                {% if current_user.is_administrator %}
                    <a href="mailto:{{ user.email }}" class="u-mail">{{ user.email }}</a>
                {% endif %}
                <div style="clear: both"></div>
                <p class="u-sign">{{ user.about_me }}</p>
            </div>

            <div class="u-edit">
                {% if current_user == user %}
                <a class="btn btn-default" href="{{ url_for('main.edit_profile') }}">编辑</a>
                {% endif %}
                {% if current_user.is_administrator %}
                    <a class="btn btn-danger" href="{{ url_for('main.edit_profile_admin', uid=user.id) }}">编辑[Admin]</a>
                {% endif %}
            </div>
        </header>

        <div class="u-nav">
            <a href="{{ url_for('main.user_space', uid=user.id) }}" class="home">
                <span class="glyphicon glyphicon-home"></span>
                <span>主页</span>
            </a>
            <a href="{{ url_for('main.user_space', uid=user.id, div='upload') }}" class="up">
                <span class="glyphicon glyphicon-expand"></span>
                <span>投稿</span>
            </a>
            <a href="{{ url_for('main.user_space', uid=user.id, div='collect') }}" class="coll">
                <span class="glyphicon glyphicon-star"></span>
                <span>收藏</span>
            </a>
            <span>
                <span class="glyphicon glyphicon-time"></span>
                <span class="u-seen">{{ user.last_seen }}</span>
            </span>
            <span>
                <span class="glyphicon glyphicon-gift"></span>
                <span class="u-id">{{ user.member_since|string|truncate(length=10, end="", leeway=0) }}</span>
            </span>
            <span>
                <span class="label">UID</span>
                <span class="u-id">{{ user.id }}</span>
            </span>
        </div>

        <div class="u-shows">
            {% for div, video in videos.items() %}
            <div class="u-videos {{ div }}">
                <h3  class="div">
                    {% if user.id == current_user.id %}{{ ['我的收藏','我的视频'][div=='upload'] }}
                    {% else %}{{ ['TA的收藏','TA的视频'][div=='collect'] }}{% endif %}
                </h3>
                <div class="storey-box">
                    {% for v in video %}
                    <div class="spread-module">
                        <a href="{{ url_for('video.play', av=v.id) }}" target="_blank">
                            <div class="lazy-img"><img src="../../static/video_faces/{{ v.face }}" alt="{{ v.title }}"/></div>
                            <div class="title">{{ v.title }}</div>
                        </a>
                        <p class="info">
                            <span class="like">
                                <span class="glyphicon glyphicon-thumbs-up"></span>
                                {{ macros.v_trunc(v.like) }}
                            </span>
                            <span class="date">
                                <span class="glyphicon glyphicon-time"></span>
                                {{ v.date|string|truncate(length=10, end="", leeway=0) }}
                            </span>
                        </p>
                    </div>
                    {% endfor %}
                    <div style="clear: both"></div>
                </div>
            </div>
            {% endfor %}
        </div>

        {% if v_div %}  {# 说明是投稿/收藏展示页，需要分页按钮 #}
        <div class="pagination">
            {{ macros.pagination_widget(pagination, 'main.user_space', uid=user.id, div=v_div) }}
        </div>
        {% endif %}
    </div>
    {{ super() }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="../../static/js/main.js"></script>
{% endblock scripts %}

app/templates/main/user_manage.html
{% extends "main/backstage.html" %}
{% import "_macros.html" as macros %}

{% block content %}
    {{ super() }}
    <div id="back-body" class="back-box">
        <table class="table">
        <tr>
            <th class="col-md-2">UID</th>
            <th class="col-md-1">头像</th>
            <th class="col-md-7">用户名</th>
            <th class="col-md-1">编辑</th>
            <th class="col-md-1">权限</th>
        </tr>
        {% for user in users %}
        <tr class="user-info">
            <td class="col-md-2">{{ user.id }}</td>
            <td class="col-md-1"><a href="{{ url_for('main.user_space', uid=user.id) }}">
                {% if not user.avatar %}
                    <img src="../../static/avatars/default.jpg" class="img-circle" alt="{{ user.nickname }}">
                {% else %}
                    <img src="../../static/avatars/{{ user.avatar }}" class="img-circle" alt="{{ user.nickname }}">
                {% endif %}
            </a></td>
            <td class="col-md-7"><a href="{{ url_for('main.user_space', uid=user.id) }}" target="_blank">
                {{ user.username }}
            </a></td>
            <td class="col-md-1">
                <a href="{{ url_for('main.edit_profile_admin', uid=user.id) }}"  target="_blank"><span class="glyphicon glyphicon-edit"></span></a>
            </td>
            <td class="col-md-1 u-perm-{{ user.permissions }}">
                {% if user.can(Permission.ADMIN) %} <span class="label label-danger">管理</span>
                {% elif user.can(Permission.AUDIT) %} <span class="label label-warning">审核</span>
                {% elif user.can(Permission.VIP) %} <span class="label label-primary">大会员</span>
                {% elif not user.permissions %} <span class="label label-default">封禁中</span>
                {% elif user.can(Permission.LOGIN) and user.can(Permission.COMMENT) %} <span class="label label-info">会员</span>
                {% elif not user.can(Permission.COMMENT) %} <span class="label label-success">禁言中</span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </table>

        <div class="pagination">
            {{ macros.pagination_widget(pagination, 'main.audit_user') }}
        </div>
    </div>
{% endblock %}

app/templates/main/video_audit.html
{% extends "main/backstage.html" %}
{% import "_macros.html" as macros %}


{% block content %}
    {{ super() }}
    <div id="back-body" class="back-box">
{#        <table class="table">#}
{#        <tr>#}
{#            <th class="col-md-1">AV</th>#}
{#            <th class="col-md-8">标题</th>#}
{#            <th class="col-md-2">上传日期</th>#}
{#            <th class="col-md-1">审核</th>#}
{#        </tr>#}
{#        {% for video in videos %}#}
{#        <tr class="up-info">#}
{#            <td class="col-md-1">{{ video.id }}</td>#}
{#            <td class="col-md-8"><a href="{{ url_for("video.play", av=video.id) }}" target="_blank" class="title">#}
{#                {{ video.title[:50] }} {% if video.title|length > 50 %}&hellip;{% endif %}#}
{#            </a></td>#}
{#            <td class="col-md-2">{{ video.date }}</td>#}
{#            <td class="col-md-1">#}
{#                <span class="glyphicon glyphicon-ok"></span>#}
{#                <span class="glyphicon glyphicon-remove"></span>#}
{#            </td>#}
{#        </tr>#}
{#        {% endfor %}#}
{#        </table>#}

        <ul class="vd-list">
        {% for v in videos %}
            <li>
                <div class="left"><a href="{{ url_for('video.play', av=v.id) }}">
                    <img src="../../static/video_faces/{{ v.face }}" alt="{{ v.title }}"/>
                </a></div>
                <div class="right">
                    <a href="{{ url_for('video.play', av=v.id) }}" target="_blank" class="title">{{ v.title }}</a>
                    <div class="up-info">
                        <a href="{{ url_for('main.user_space', uid=v.author_id) }}" class="v-author">{{ v.author.username }}</a>
                        <span class="v-date">{{ v.date }}</span>
                    </div>
                    <div class="v-desc">{% if v.desc%}{{ v.desc }}{% else %}{{ "视频简介吧."*37 }}{% endif %}</div>
                    <div class="v-stat">
                        <span title="点赞数" class="like">
                            <span class="glyphicon glyphicon-thumbs-up"></span>
                            <span class="statistic">{{ macros.v_trunc(v.like) }}</span>
                        </span>
                        <span title="硬币数" class="coin">
                            <span class="glyphicon glyphicon-copyright-mark"></span>
                            <span class="statistic">{{ macros.v_trunc(v.coin) }}</span>
                        </span>
                        <span title="收藏数" class="collect">
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="statistic">{{ macros.v_trunc(v.collect) }}</span>
                        </span>
                    </div>

                    <div class="v-audit">
                        <span class="glyphicon glyphicon-remove"></span>
                        <span class="glyphicon glyphicon-ok"></span>
                    </div>

                </div>
            </li>
        {% endfor %}
        </ul>

        <div class="pagination">
            {{ macros.pagination_widget(pagination, 'main.audit_video') }}
        </div>
    </div>
{% endblock %}